### ISSUE TITLE
Error: Placing item from inventory on the background

### ISSUE THREAD

**Issue by Piechutowski** [Zaloog/idle-tui-adventures#1]
When placing an item between containers, an `AttributeError: 'InventoryEquipScreen' object has no attribute 'place_item'` occurs.
![Screenshot_20240810_105216](https://github.com/user-attachments/assets/188075df-537b-4b98-b77a-5fc5313e5cb6)

**Comment by Zaloog** [comment]
good catch :)
fixed with f9d3d09
